name: Test ansible role on Debian

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  python2:

    runs-on: ubuntu-latest
    container: python:2.7.18-alpine
    strategy:
      matrix:
        distribution: 
          - debian
        dist_version: 
          - 9-builded
        mongodb_version:
          - '4.2'
          - '4.0'
          - '3.6'
    env:
      DISTRIBUTION: ${{ matrix.distribution }}
      DIST_VERSION: ${{ matrix.dist_version }}
      MONGODB_VERSION: ${{ matrix.mongodb_version }}
      DOCKER_PRIVILEGED: true
      PYTHON_VERSION: '2'
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare tests
        run: |
          apk add --no-cache bash
          bash tests/scripts/before_install.sh

      - name: Run test on single host and security authorization disabled
        run: bash tests/scripts/single.sh disabled python
      - name: Run idempotence test and cleanup
        run: bash tests/scripts/single_cleanup.sh disabled python

      - name: Run test on single host and security authorization enabled
        run: bash tests/scripts/single.sh enabled python
      - name: Run idempotence test and cleanup
        run: bash tests/scripts/single_cleanup.sh enabled python

      - name: Run test replicaSet on three hosts and security authorization disabled
        run: bash tests/scripts/rs.sh disabled python
      - name: Run idempotence test and cleanup
        run: bash tests/scripts/rs_cleanup.sh disabled python

      - name: Run test replicaSet on three hosts and security authorization enabled
        run: bash tests/scripts/rs.sh enabled python
      - name: Run idempotence test and cleanup
        run: bash tests/scripts/rs_cleanup.sh enabled python


  python3:

    runs-on: ubuntu-latest
    container: python:3.8.3-alpine
    strategy:
      matrix:
        distribution:
          - debian
        dist_version:
          - 10-builded
        mongodb_version:
          - '4.2'
    env:
      DISTRIBUTION: ${{ matrix.distribution }}
      DIST_VERSION: ${{ matrix.dist_version }}
      MONGODB_VERSION: ${{ matrix.mongodb_version }}
      DOCKER_PRIVILEGED: true
      PYTHON_VERSION: '3'
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare tests
        run: |
          apk add --no-cache bash
          bash tests/scripts/before_install.sh

      - name: Run test on single host and security authorization disabled
        run: bash tests/scripts/single.sh disabled python3
      - name: Run idempotence test and cleanup
        run: bash tests/scripts/single_cleanup.sh disabled python3

      - name: Run test on single host and security authorization enabled
        run: bash tests/scripts/single.sh enabled python3
      - name: Run idempotence test and cleanup
        run: bash tests/scripts/single_cleanup.sh enabled python3

      - name: Run test replicaSet on three hosts and security authorization disabled
        run: bash tests/scripts/rs.sh disabled python3
      - name: Run idempotence test and cleanup
        run: bash tests/scripts/rs_cleanup.sh disabled python3

      - name: Run test replicaSet on three hosts and security authorization enabled
        run: bash tests/scripts/rs.sh enabled python3
      - name: Run idempotence test and cleanup
        run: bash tests/scripts/rs_cleanup.sh enabled python3

